config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories do
    member do
      get "like", to: "stories#upvote"
      get "dislike", to: "stories#downvote"
    end
    resources :comments
  end

  root "stories#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#>", small: "370x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @story = Story.find(params[:story_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.story_id = @story.id

    if @comment.save
      redirect_to story_path(@story)
    else
      render 'new'
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :find_story, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @stories = Story.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(story_id: @story)
  end

  def new
    @story = current_user.stories.build
  end

  def create
    @story = current_user.stories.build(story_params)

    if @story.save
      redirect_to @story, notice: "Successfully Created New Story"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to @story, notice: "Story was Successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @story.destroy
      redirect_to root_path
  end

  def upvote
    @story.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @story.downvote_by current_user
    redirect_to :back
  end

  private

  def story_params
    params.require(:story).permit(:title, :link, :description, :image)
  end

  def find_story
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@story, @story.comments.build]) do |f|
  = f.input :content, label: "Discuss Your View"
  = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Podium
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag :defaults
  %link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css"}
  %link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
  = csrf_meta_tags

  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      #logo= link_to "Podium", root_path
      - if user_signed_in?
        = link_to current_user.name, edit_user_registration_path, class: "button"
        -# = link_to "New Story", new_story_path, class: "button"
        = link_to "Sign Out", destroy_user_session_path, :method => 'delete', class: "button"
      - else
        = link_to "Sign In", new_user_session_path, class: "button"
        = link_to "Sign Up", new_user_registration_path, class: "button"

%body
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/stories/_form.html.haml
= simple_form_for @story do |f|
  = f.input :image
  = f.input :title
  = f.input :link
  = f.input :description

  = f.button :submit

app/views/stories/edit.html.haml
%h1 Edit Story

= render 'form'

= link_to "Cancel", story_path

app/views/stories/index.html.haml
- if user_signed_in?
  %p#intro
    Hello,
    = current_user.name
    %br/
    %span
      Share and discuss your views on the Top News Stories around the world, with others.
- else
  %p#intro
    What's your Stance?
    %br/
    %span
      Sign In or SignUp, Share and discuss your views on the Top News Stories around the world, with others.
.container
  .row
    .col-lg-12
      %h1.page-header
        Top Stories
  .row.text-center
    - @stories.each do |story|
      .col-md-4.col-sm-6.hero-feature
        .thumbnail
          %img= link_to (image_tag story.image.url(:small)), story, class: "img-responsive"
          .caption
            .title
              %h2= link_to story.title, story
          %p.buttons
            %span
              %i.fa.fa-comments-o
            = story.comments.count
            %span.likes
              %i.fa.fa-thumbs-o-up
              = story.get_likes.size

app/views/stories/new.html.haml
%h1 New Form

= render 'form'

= link_to "Back", root_path

app/views/stories/show.html.haml
.container
  .row
    .col-md-9
      .thumbnail
        = image_tag @story.image.url(:medium)
        .caption-full
          %h1= @story.title
          .story_data
          = link_to like_story_path(@story), method: :get, class: "data" do
            %i.fa.fa-thumbs-o-up
            = pluralize(@story.get_upvotes.size, "Like")
          = link_to dislike_story_path(@story), method: :get, class: "data" do
            %i.fa.fa-thumbs-o-down
            = pluralize(@story.get_downvotes.size, "Dislike")
          %p.data
            %i.fa.fa-comments-o
            = pluralize(@story.comments.count, "Comments")
          - if @story.user == current_user
            = link_to "Edit", edit_story_path(@story), class: "data"
            = link_to "Delete", story_path(@story), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
          %p
            .description= simple_format(@story.description)

    .col-md-3
      .text-right
        %h2.comment_count= pluralize(@story.comments.count, "Comment")
      .list-group
        .well
          .text-left
            = render "comments/form"
          %hr/
          .row
            .col-md-12
            - @comments.each do |comment|
              .comment
                %p.username= comment.user.name
                %p.content= comment.content
                %hr/